### ISSUE TITLE
不要将IDE配置文件和特定于本地的配置文件提交到github

### ISSUE THREAD

**Issue by ggd543** [oschina/android-app#1]
不要将IDE配置文件和特定于本地的配置文件提交到github，因为checkout到本地后，导入eclipse工程可能会出现问题。只需将源代码提交就好了，中间代码、日志文件、临时文件等不要提交

**Comment by lifw555** [comment]
IDE的配置文件还是要提交的吧，要不编码和配置容易对不上，容易混乱。

**Comment by c61811** [comment]
import android.annotation.TargetApi;

这个找不到,是什么原因呢?

**Comment by jxsmallmouse** [comment]
To : c61811

你的Android SDK的版本和ADT的版本较低了
