### ISSUE TITLE
滑动加载数据bug

### ISSUE THREAD

**Issue by kongnanlive** [oschina/android-app#12]
缓慢向上划动视图，到达底部后，自动加载“更多”数据，此时会重复加载1-3次.
解决办法：
在
if(scrollEnd && lvDataState==UIHelper.LISTVIEW_DATA_MORE && scrollState == AbsListView.OnScrollListener.SCROLL_STATE_IDLE)
                {
                    lvNews_foot_more.setText(R.string.load_ing);
                    lvNews_foot_progress.setVisibility(View.VISIBLE);
                    //当前pageIndex
                    int pageIndex = lvNewsSumData/AppContext.PAGE_SIZE;
                    loadLvNewsData(curNewsCatalog, pageIndex, lvNewsHandler, UIHelper.LISTVIEW_ACTION_SCROLL);
                }
除加上 && scrollState == AbsListView.OnScrollListener.SCROLL_STATE_IDLE
解决了。

**Comment by jxsmallmouse** [comment]
感谢你对OSChina Android客户端的关注，我要先做测试再决定是否合并你的代码 ：）

**Comment by jxsmallmouse** [comment]
@kongnanlive  我测试了下，暂时没有遇到你说的那个情况哦。

**Comment by kongnanlive** [comment]
@jxsmallmouse 亲，测试机型联想乐phone，华为P1，三星I9100.代码我一点没动，3个机型都出这样的问题，我用的debug模式在loadLvNewsData(curNewsCatalog, pageIndex, lvNewsHandler, UIHelper.LISTVIEW_ACTION_SCROLL);处添加断点,手指猛地向上滑动，还好不会出现问题，但是当手指缓慢向上滑动屏幕，视图到达底部时断点会触发1-3次，也就是会发起http请求1-3次，至于你为什么没有测出来，我怀疑是没有在loadLvNewsData出添加断点。

**Comment by jxsmallmouse** [comment]
@kongnanlive 非常感谢，你说的问题确实存在，现已修复了：）
