### ISSUE TITLE
ListItem选中状态下背景色不变bug

### ISSUE THREAD

**Issue by kongnanlive** [oschina/android-app#13]
这个只是用户体验的不良的bug

如何产生：
手指点中一列，该列白色背景色变成浅蓝色后，不要松开手指，向左或向右移动，直到移出触摸屏，会发现，浅蓝色背景依然是浅蓝色，而没有恢复原来的白色背景色。

对比其他：
新浪微薄Android客户端就不会出现这种情况。

个人：
另外，测试发现等待“新闻正文”的时候，有时会有1-2s的延迟，这时候item的背景色依然是浅蓝色的。

ps：我认为手指松开item的背景色应该恢复原来的颜色啊？！对吗

**Comment by jxsmallmouse** [comment]
@kongnanlive 你好，我暂时没有发现你说的现象，请问你用的手机型号和android系统版本号是多少?
